language: python
python:
  - 2.6
  - 2.7
  - 3.3
env:
  - DJANGO_VERSION=1.4.8
  - DJANGO_VERSION=1.5.4
install:
  - pip install Django==$DJANGO_VERSION
  - pip install -r testproject/requirements.txt
  - pip install -r testproject/requirements_test.txt
  - python setup.py install
script:
  - cd testproject
  - python manage.py test django_file_form_example
  - coverage run --source=django_file_form,django_file_form_example manage.py test django_file_form_example
  - coverage report
after_success:
  - pip install -r requirements_coveralls.txt
  - coveralls
matrix:
  exclude:
    - python: 3.3
      env: DJANGO_VERSION=1.4.8