language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - pypy
env:
  - DJANGO=Django==1.7.8
  - DJANGO=Django==1.8.1
install:
  - pip install $DJANGO
  - pip install -r testproject/requirements.txt
  - pip install -r testproject/requirements_test.txt
  - pip install -r testproject/requirements_travis.txt
  - pip install -e .
script:
  - python testproject/manage.py test django_file_form_example
  - coverage run --source=django_file_form,testproject/django_file_form_example testproject/manage.py test django_file_form_example
  - coverage report
after_success:
  - coveralls
matrix:
  exclude:
    - python: pypy
      env: DJANGO=Django==1.8.1
